/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package swing;
import DTO.DataSearchDTO;
import java.awt.Component;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import net.miginfocom.swing.MigLayout;
//import net.miginfocom.swing.MigLayout;
/**
 *
 * @author Admin
 */
public class PanelSearch extends javax.swing.JPanel {

    /**
     * Creates new form PanelSearch
     */
    private EventClick event;
    private int selectedIndex = -1;
    public void addEventClick(EventClick e){
        this.event = e;
    }
    public PanelSearch() {
        initComponents();
        setLayout(new MigLayout("fillx", "0[]0", "0[]0"));
    }
    public void setData(List<DataSearchDTO> data)
    {
        selectedIndex = -1;
	this.removeAll();
	for (DataSearchDTO temp :data)
	{
            Search_Item item = new Search_Item(temp);
            item.addEvent(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    event.itemClick(temp);
                }
                
            }, new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    event.itemRemove(item, temp);
                }
            }
            );
            this.add(item, "wrap");
			
	}
	repaint();
	revalidate();
    }
    public int getItemSize()
    {
	return getComponentCount();
    }
    public void KeyUp(){
        int size = getItemSize();
        if (size > 0){
          if (selectedIndex <= 0) 
              selectedIndex = size;
          else
              selectedIndex--;
        }
        showSelected();
    }
    public void KeyDown(){
        int size = getItemSize();
        if (size > 0){
          if (selectedIndex >= size -1 ) 
              selectedIndex = 0;
          else
              selectedIndex++;
        }
        showSelected();
    }
    public String getItemSelected(){
        if (selectedIndex != -1  && selectedIndex < getComponentCount()){
            return ((Search_Item)getComponent(selectedIndex)).getText();
        }
        return "";
    }
    public void showSelected(){
        Component com[] = getComponents();
        for (int i = 0; i < com.length; i ++){
            ((Search_Item) com[i]).setSelected(i == selectedIndex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 226, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
