/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package swing;

import DTO.DataSearchDTO;
import java.awt.Color;
import java.awt.Component;
import java.awt.Cursor;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author Admin
 */
public class Search_Item extends javax.swing.JPanel {

    /**
     * Creates new form Search_Item
     */
    public Search_Item(DataSearchDTO data)
    {
	initComponents();
	setData(data);
		
    }
    public void setData(DataSearchDTO data)
    {
        addEventMouse(this);
        addEventMouse(lbText);
        addEventMouse(lbRemove);
	lbText.setText(data.getText());
	if (data.isStory())
	{
            lbText.setForeground(new Color(29, 106, 205));
            lbRemove.setCursor(new Cursor(Cursor.HAND_CURSOR));
	}
	else
	{
            lbRemove.setText("");
                
            //lblNewLabel.setIcon(new ImageIcon(getClass().getResource("/image/Iconshock-Real-Vista-Text-Search-b.16.png")));
	}
    }
    public void addEventMouse(Component com){
        com.addMouseListener(new MouseAdapter(){
        @Override
        public void mouseEntered(MouseEvent me){
            setBackground(new Color(215, 216, 216));
        }
        @Override
        public void mouseExited(MouseEvent me){
            setBackground(Color.WHITE);
        }
        });
    }
    private ActionListener eventClick;
    private ActionListener eventRemove;
    //private int a;
    public void addEvent(ActionListener eventClick, ActionListener eventRemove){
        this.eventClick = eventClick;
        this.eventRemove = eventRemove;
        
    }
    
//    private void addEventMouse(Component com)
//    {
//        
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbRemove = new javax.swing.JLabel();
        lbSearch = new javax.swing.JLabel();
        lbText = new javax.swing.JLabel();

        lbRemove.setText("Remove");

        setBackground(new java.awt.Color(255, 255, 255));

        lbSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Iconshock-Real-Vista-Text-Search-b.32.png"))); // NOI18N

        lbText.setText("Text....");
        lbText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbTextMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbText, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lbTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbTextMouseClicked
        // TODO add your handling code here:
        eventClick.actionPerformed(null);
    }//GEN-LAST:event_lbTextMouseClicked
    public String getText(){
        return lbText.getText();
    }
    public void setSelected(boolean act){
        if(act)
            setBackground(new Color(215, 216, 216));
        else
            setBackground(Color.WHITE);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbRemove;
    private javax.swing.JLabel lbSearch;
    private javax.swing.JLabel lbText;
    // End of variables declaration//GEN-END:variables
}
